# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  http_method_override: false

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  #esi: true
  #fragments: true
  php_errors:
    log: true

  http_client:
    scoped_clients:
      airtable.client:
        base_uri: https://api.airtable.com/v0/
        headers:
          Accept: 'application/json'
          Authorization: 'Bearer %env(AIRTABLE_API_KEY)%'
      meteo.client:
        base_uri: https://api.meteo-concept.com/api/
        query:
          token: '%env(METEO_API_TOKEN)%'
        headers:
          Accept: 'application/json'
      twitter.client:
        base_uri: https://api.twitter.com/2/
        headers:
          Authorization: 'Bearer %env(TWITTER_API_TOKEN_BEARER)%'
      ecoresponsablegouv.client:
        base_uri: https://ecoresponsable.numerique.gouv.fr/
      inr.client:
        base_uri: https://sustainableit-tools.isit-europe.org/
      githubrepository.client:
        base_uri: https://api.github.com/repos/jcognet/airtable_sf/
        headers:
          Accept: 'application/vnd.github.v3+json'
          Authorization: 'token %env(GITHUB_API_TOKEN)%'
      currency.client:
        base_uri: http://api.exchangeratesapi.io/v1/
        query:
          access_key: '%env(EXCHANGE_RATES_API_IO_KEY)%'
      lpo.client:
        base_uri: https://www.oiseauxdesjardins.fr/index.php

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
