security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory:
          memory:
            users:
              jcognet: { password: '$2y$13$geEXiKQSBsX1ESN2Ryvx/eW21uC6yQzpEAqyEdhxhRFx9qckqfHgG', roles: ['ROLE_USER'] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            http_basic:
              realm: Secured Area
            login_link:
              check_route: login_check
              signature_properties: ['UserIdentifier']
              lifetime: 86400

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/git/*, roles: PUBLIC_ACCESS }
        - { path: ^/img/thumbnail/*, roles: PUBLIC_ACCESS }
        - { path: ^/img/normal/*, roles: PUBLIC_ACCESS }
        - { path: ^/img/list, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
