twig:
  default_path: '%kernel.project_dir%/templates'

  globals:
    url_front: '%env(URL_ABSOLUTE_FRONT)%'
    ecoresponsablegouv_base_url: '%ecoresponsaglegouvBaseUrl%'
    lpo_base_url: '%lpoBaseUrl%'
    inr_491_base_url: '%inr491BaseUrl%'

when@test:
  twig:
    strict_variables: true
