version: '3'

networks:
    nginx-php74:

services:
    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./back:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
        networks:
            - nginx-php74

    # php
    php74-service:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./back:/var/www/project
        networks:
            - nginx-php74
