version: '3'

networks:
  airtable:

services:
  # php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./back:/var/www/project
    networks:
      - airtable
