version: '3'

networks:
  airtable:

services:
  # nginx
  airtable_nginx:
    image: nginx:stable-alpine
    container_name: airtable_nginx
    ports:
      - "7000:80"
    volumes:
      - ./back:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - airtable_php
    networks:
      - airtable

  # php
  airtable_php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: airtable_php
    volumes:
      - ./back:/var/www/project
    networks:
      - airtable
