# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  inr491BaseUrl: 'https://gr491.isit-europe.org/'
  ecoresponsaglegouvBaseUrl: 'https://ecoresponsable.numerique.gouv.fr/'
  lpoBaseUrl: 'https://www.oiseauxdesjardins.fr/index.php'
  passportBaseUrl: 'https://rendezvouspasseport.ants.gouv.fr/'
  thumbnail_list:
    default:
      height: 200
      width: 200
    newsletter_width:
      height: 750
      width: 500
    list_beer:
      height: 350
      width: 350
    main_image:
      width: 500
      height: 400
    main_image_previous:
      width: 400
      height: 200

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $airtableAppArticleId: '%env(AIRTABLE_APP_ARTICLE_ID)%'
      $airtableAppBiereId: '%env(AIRTABLE_APP_BIERE_ID)%'
      $airtableAppToDoId: '%env(AIRTABLE_APP_TO_DO_ID)%'
      $airtableAppBookId: '%env(AIRTABLE_APP_BOOK_ID)%'
      $airtableAppRunId: '%env(AIRTABLE_APP_RUN_ID)%'
      $mailerFrom: '%env(MAILER_FROM)%'
      $mailerTo: '%env(MAILER_TO)%'
      $projectDir: '%kernel.project_dir%'
      $githubSecret: '%env(GITHUB_SECRET)%'
      $pathToConfigurationYaml: '%kernel.project_dir%/config/blocks/'
      $deployJsonPath: '%kernel.project_dir%/src/Data/deploy.json'
      $deployArchiveJsonPath: '%kernel.project_dir%/src/Data/archive/'
      $birdPath: '%kernel.project_dir%/src/Data/bird/'
      $pathPictures: '%kernel.project_dir%/src/Data/photo/'
      $googleCredentialFile: '%kernel.project_dir%/config/google_credential.json'
      $spreadSheetAirtableId: '%env(GOOGLE_SPREADSHEET_EXPORT_ID)%'
      $progressContentUrl: '%env(GOOGLE_PROGRESS_CONTENT_URL)%'
      $doneContentUrl: '%env(GOOGLE_DONE_CONTENT_URL)%'
      $pdfApiKey: '%env(PDF_API_KEY)%'
      $environment: '%kernel.environment%'
      $thumbnailList: '%thumbnail_list%'
      $absoluteUrlFront: '%env(URL_ABSOLUTE_FRONT)%'
      $inr491BaseUrl: '%inr491BaseUrl%'
      $cachedImagePath: '%kernel.project_dir%/src/Data/cached_image/'
      $passportBaseUrl: '%passportBaseUrl%'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'
      - '../src/ValueObject/'

  _instanceof:
    App\Service\Block\BlockManagerInterface:
      tags: [ 'app.block_manager' ]

    App\Service\Repository\Random\RandomImageRepositoryInterface:
      tags: [ 'app.random_image_repository' ]

    App\Service\Contract\CleanerInterface:
      tags: [ 'app.cleaner' ]

  App\Service\NewsletterManager\ManagerContentFactory:
    arguments:
      - !tagged_iterator app.block_manager

  App\Service\Block\Random\RandomPicBlockManager:
    arguments:
      - !tagged_iterator app.random_image_repository

  App\Command\CleanDataCommand:
    arguments:
      - !tagged_iterator app.cleaner

  App\Service\Security\LoginLinkHandler:
    arguments:
      $loginLinkHandler: '@security.authenticator.login_link_handler.main'

when@test:
  services:
    _defaults:
      bind:
        $deployArchiveJsonPath: '%kernel.project_dir%/tests/data/'
