# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  deployArchiveJsonPath: '%kernel.project_dir%/src/Data/'
  deployJsonPath: '%kernel.project_dir%/src/Data/deploy.json'
  inr491BaseUrl: 'https://gr491.isit-europe.org/'
  ecoresponsaglegouvBaseUrl: 'https://ecoresponsable.numerique.gouv.fr/'
  lpoBaseUrl: 'https://www.oiseauxdesjardins.fr/index.php'
  thumbnail_list:
    default:
      height: 200
      width: 200
    newsletter_width:
      height: 750
      width: 500
    list_beer:
      height: 350
      width: 350
    main_image:
      width: 500
      height: 400
    main_image_previous:
      width: 400
      height: 200

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $airtableAppArticleId: '%env(AIRTABLE_APP_ARTICLE_ID)%'
      $airtableAppBiereId: '%env(AIRTABLE_APP_BIERE_ID)%'
      $airtableAppToDoId: '%env(AIRTABLE_APP_TO_DO_ID)%'
      $airtableAppBookId: '%env(AIRTABLE_APP_BOOK_ID)%'
      $airtableAppRunId: '%env(AIRTABLE_APP_RUN_ID)%'
      $airtableAppQcmId: '%env(AIRTABLE_APP_QCM_ID)%'
      $airtableAppHollidayId: '%env(AIRTABLE_APP_HOLLIDAY_ID)%'
      $airtableAppClientId: '%env(AIRTABLE_APP_FILE_ID)%'
      $airtableAppFoodingId: '%env(AIRTABLE_APP_FOODING_ID)%'
      $mailerFrom: '%env(MAILER_FROM)%'
      $mailerTo: '%env(MAILER_TO)%'
      $projectDir: '%kernel.project_dir%'
      $githubSecret: '%env(GITHUB_SECRET)%'
      $secret: '%env(APP_SECRET)%'
      $pathToConfigurationYaml: '%kernel.project_dir%/config/blocks/'
      $deployJsonPath: '%deployJsonPath%'
      $deployArchiveJsonPath: '%deployArchiveJsonPath%'
      $birdPath: '%kernel.project_dir%/src/Data/bird/'
      $picturePath: '%kernel.project_dir%/src/Data/photo/'
      $filePath: '%kernel.project_dir%/src/Data/file/'
      $childrenPath: '%kernel.project_dir%/src/Data/children/'
      $googleCredentialFile: '%kernel.project_dir%/config/google_credential.json'
      $spreadSheetAirtableId: '%env(GOOGLE_SPREADSHEET_EXPORT_ID)%'
      $spreadSheetNurseryId: '%env(GOOGLE_NURSERY_EXPORT_ID)%'
      $progressContentUrl: '%env(GOOGLE_PROGRESS_CONTENT_URL)%'
      $doneContentUrl: '%env(GOOGLE_DONE_CONTENT_URL)%'
      $pdfApiKey: '%env(PDF_API_KEY)%'
      $environment: '%kernel.environment%'
      $thumbnailList: '%thumbnail_list%'
      $absoluteUrlFront: '%env(URL_ABSOLUTE_FRONT)%'
      $inr491BaseUrl: '%inr491BaseUrl%'
      $cachedImagePath: '%kernel.project_dir%/src/Data/cached_image/'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'
      - '../src/ValueObject/'

  _instanceof:
    App\Service\Block\BlockManagerInterface:
      tags: [ 'app.block_manager' ]

    App\Service\Alert\AlerterInterface:
      tags: [ 'app.alerter' ]

    App\Service\Repository\Random\RandomImageRepositoryInterface:
      tags: [ 'app.random_image_repository' ]

    App\Service\Contract\CleanerInterface:
      tags: [ 'app.cleaner' ]

    App\Service\Contract\AirtableImporterInterface:
      tags: [ 'app.airtable_importer' ]

    App\Service\Contract\AirtableConfigInterface:
      tags: [ 'app.airtable_config' ]

  App\Service\NewsletterManager\ManagerContentFactory:
    arguments:
      - !tagged_iterator app.block_manager

  App\Service\Alert\Alerter:
    arguments:
      - !tagged_iterator app.alerter

  App\Service\Block\Random\RandomPicBlockManager:
    arguments:
      - !tagged_iterator app.random_image_repository

  App\Command\CleanDataCommand:
    arguments:
      - !tagged_iterator app.cleaner

  App\Service\Import\Airtable\AllImporter:
    arguments:
      - !tagged_iterator app.airtable_importer

  App\Service\Import\Airtable\IsImported:
    arguments:
      - !tagged_iterator app.airtable_config

  App\Service\Import\Airtable\Factory\ConfigFactory:
    arguments:
      - !tagged_iterator app.airtable_config

  App\Command\Test\CreateAllJsonCommand:
    arguments:
      $importers: !tagged_iterator app.airtable_importer

  App\Service\Security\LoginLinkHandler:
    arguments:
      $loginLinkHandler: '@security.authenticator.login_link_handler.main'

  App\Service\Import\Airtable\Qcm\Question\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Qcm\Question\Config'

  App\Service\Import\Airtable\Holiday\Holiday\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Holiday\Holiday\Config'

  App\Service\Import\Airtable\Run\NextRun\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Run\NextRun\Config'

  App\Service\Import\Airtable\Article\ALire\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Article\ALire\Config'

  App\Service\Import\Airtable\Article\SeeAgain\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Article\SeeAgain\Config'

  App\Service\Import\Airtable\File\File\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\File\File\Config'

  App\Service\Import\Airtable\Book\Book\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Book\Book\Config'

  App\Service\Import\Airtable\Fooding\Coffee\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Coffee\Config'

  App\Service\Import\Airtable\Fooding\Meat\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Meat\Config'

  App\Service\Import\Airtable\Fooding\Cut\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Cut\Config'

  App\Service\Import\Airtable\Fooding\Abs\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Abs\Config'

  App\Service\Import\Airtable\Fooding\Coloring\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Coloring\Config'

  App\Service\Import\Airtable\Fooding\Qi\Lister:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Qi\Config'

  App\Service\Import\Airtable\Holiday\Holiday\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Holiday\Holiday\Config'
      $client: '@App\Service\AirTable\Holiday\HolidayClient'

  App\Service\Import\Airtable\Qcm\Question\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Qcm\Question\Config'
      $client: '@App\Service\AirTable\Qcm\QuestionClient'

  App\Service\Import\Airtable\Run\NextRun\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Run\NextRun\Config'
      $client: '@App\Service\AirTable\Run\RunClient'

  App\Service\Import\Airtable\Article\ALire\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Article\ALire\Config'
      $client: '@App\Service\AirTable\Article\ALireClient'

  App\Service\Import\Airtable\Article\SeeAgain\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Article\SeeAgain\Config'
      $client: '@App\Service\AirTable\Article\SeeAgainClient'

  App\Service\Import\Airtable\File\File\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\File\File\Config'
      $client: '@App\Service\AirTable\File\FileClient'

  App\Service\Import\Airtable\Book\Book\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Book\Book\Config'
      $client: '@App\Service\AirTable\Book\BookClient'

  App\Service\Import\Airtable\Fooding\Coffee\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Coffee\Config'
      $client: '@App\Service\AirTable\Fooding\CoffeeClient'

  App\Service\Import\Airtable\Fooding\Meat\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Meat\Config'
      $client: '@App\Service\AirTable\Fooding\MeatClient'

  App\Service\Import\Airtable\Fooding\Cut\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Cut\Config'
      $client: '@App\Service\AirTable\Fooding\CutClient'

  App\Service\Import\Airtable\Fooding\Abs\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Abs\Config'
      $client: '@App\Service\AirTable\Fooding\AbsClient'


  App\Service\Import\Airtable\Fooding\Coloring\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Coloring\Config'
      $client: '@App\Service\AirTable\Fooding\ColoringClient'

  App\Service\Import\Airtable\Fooding\Qi\Importer:
    arguments:
      $config: '@App\Service\Import\Airtable\Fooding\Qi\Config'
      $client: '@App\Service\AirTable\Fooding\QiClient'

when@test:
  parameters:
    deployArchiveJsonPath: '%kernel.project_dir%/tests/data/'
    deployJsonPath: '%kernel.project_dir%/tests/data/test/deploy_result.json'
