blocks:
  - bot_doux
  - article
  - image
  - concept
  - good_practice_organization
  - see_againl
  - list_meteo
  - list_todo
  - image_url
  - list_article
  - image_list_pictures
  - video
  - inr_491
  - list_article_read
  - list_interesting_topic
  - rgsen
  - list_bird
  - list_inr_tool
  - list_beer
