blocks:
  - bot_doux
  - article
  - image
  - good_practice_organization
  - list_book
  - list_meteo
  - list_todo
  - image_url
  - list_article
  - video
  - list_article_read
  - list_interesting_topic
  - rgsen
  - list_inr_tool
  - list_beer
