blocks:
  - article
  - image
  - concept
  - see_again
  - list_meteo
  - list_todo
  - image_url
  - list_article
  - image_list_pictures
  - video
  - inr_491
  - list_article_read
  - list_interesting_topic
  - rgesn
  - quiz
  - list_bird
  - list_inr_tool
  - list_beer
