blocks:
  - image
  - bot_doux
  - list_meteo
  - passport
  - list_todo
  - image_google_in_progess
  - image_url
  - list_beer
  - image_google_done
  - see_again
  - image_google_currencies
  - next_runs
  - image_list_pictures
