blocks:
  - image
  - list_meteo
  - list_todo
  - image_google_in_progess
  - image_url
  - quiz
  - list_beer
  - image_google_done
  - see_again
  - next_runs
  - image_list_pictures
  - list_interesting_topic
